services:
  mplab_ide:
    build:
      context: .
    container_name: mplab-ide
    extends:
      file: common.yml
      service: x11
    environment:
      HOME: /home/developer
    user: 1000:100
    volumes:
    - ./home:/home/developer:rw
version: '2.1'
